# Production shared overrides (used by blue/green/www releases)
testServer:
  enabled: false

# Enable monitoring for production
monitoring:
  enabled: true
  grafana:
    enabled: true
  prometheus:
    enabled: true

nginx:
  replicas: 2
  runtimeConfig:
    enabled: true
  env:
    APP_VERSION: "{{ .Chart.Version }}"
    NODE_ENV: "production"
  resources: {}
  # Example:
  # resources:
  #   requests: { cpu: "100m", memory: "128Mi" }
  #   limits:   { cpu: "500m", memory: "256Mi" }

connector:
  replicas: 2
  resources: {}
  # Example:
  # resources:
  #   requests: { cpu: "200m", memory: "256Mi" }
  #   limits:   { cpu: "1", memory: "512Mi" }

udp:
  replicas: 1
  env:
    AI_MODE: "gpt"
    # Override DB settings from secret (external Azure PostgreSQL)
    DB_HOST: "udpchatnewpg.postgres.database.azure.com"
    DB_PORT: "5432"
    DB_NAME: "udpchat"
    DB_USER: "pgadmin"
  resources: {}
  httpStatus:
    enabled: false  # flip to true for an HTTP health endpoint in prod
