# Testing env overrides
deployTarget: "testing"

# Use fewer replicas by default in testing
nginx:
  replicas: 1
  env:
    APP_VERSION: "testing"
    NODE_ENV: "testing"

connector:
  replicas: 1
  env: {}

udp:
  replicas: 1
  port: 9999
  env:
    DB_HOST: "postgres"
    DB_PORT: "5432"
    DB_NAME: "udpchat"
    DB_USER: "udpchat"
    AI_MODE: "gpt"

# For testing, auto-create secret if it doesn't exist
# If secret.testing.yaml is pre-applied, it takes precedence
existingAppSecret:
  enabled: false  # Let Helm create it if needed
  name: udpchat-app

# Auto-provision secret with default values for local development
# For security, pass sensitive values via --set or create secret.testing.yaml from sample
appSecret:
  enabled: true
  name: udpchat-app
  data:
    DB_HOST: "postgres"
    DB_PORT: "5432"
    DB_NAME: "udpchat"
    DB_USER: "udpchat"
    DB_PASSWORD: "" # Set via secrets
    OPENAI_API_KEY: ""  # Set via secrets

# Postgres config: read password from udpchat-app key DB_PASSWORD
testing:
  tlsEnabled: true
  db:
    passwordKey: DB_PASSWORD

# Certificate defaults for testing (HTTP-01 via ClusterIssuer)
certificate:
  create: true
  secretName: udpchat-testing-tls
  issuer:
    kind: ClusterIssuer
    name: letsencrypt-prod

