{{- if .Values.nginx.runtimeConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "udpchat.fullname" . }}-nginx-runtime
  labels:
    {{- include "udpchat.labels" . | nindent 4 }}
data:
  # Nginx default server that adds /api/config as a static JSON file
  default.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        keepalive_timeout  65;

        # Gzip compression
        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types
            text/plain
            text/css
            text/xml
            text/javascript
            application/javascript
            application/xml+rss
            application/json;

        # Define connection upgrade variable for WebSocket support
        map $http_upgrade $connection_upgrade {
            default upgrade;
            '' close;
        }

        server {
            listen 80;
            server_name _;
            root /usr/share/nginx/html;
            index index.html;

            # Health for probes
            location = /healthz { return 200; }

            # Runtime configuration as JSON
            location = /api/config {
                default_type application/json;
                add_header Cache-Control "no-store";
                try_files /etc/nginx/runtime/config.json =404;
            }

            # WebSocket to connector
            location /ws {
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_http_version 1.1;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_read_timeout 3600;
                proxy_pass http://{{ include "udpchat.name.connector" . }}:{{ default 8001 .Values.connector.port }};
            }


            # Cache static assets
            location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
                expires 1y;
                add_header Cache-Control "public, immutable";
            }

            # Health check endpoints
            location = /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }

            # static site
            location / {
                try_files $uri $uri/ /index.html;
            }
        }
    }

  # Template rendered by envsubst at startup into /etc/nginx/runtime/config.json
  config.json.tmpl: |
    {
      "appVersion": "${APP_VERSION:-}",
      "nodeEnv": "${NODE_ENV:-production}"
    }
{{- end }}
