{{- if and (include "udpchat.isTesting" . | ne "true") .Values.monitoring.grafana.enabled }}
{{- $active := include "udpchat.activeColour" . -}}
{{- $deployTarget := default "" .Values.deployTarget | lower -}}
{{- if eq $deployTarget $active }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "udpchat.fullname" . }}-grafana
  labels:
    {{- include "udpchat.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/color: {{ $active | quote }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts: [ grafana.{{ include "udpchat.host.root" . }} ]
      secretName: {{ include "udpchat.tlsSecretName" . }}
  rules:
    - host: grafana.{{ include "udpchat.host.root" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "udpchat.name.grafana" . }}
                port: { number: 3000 }
{{- end }}
{{- end }}
