{{- if and (include "udpchat.isTesting" . | ne "true") .Values.monitoring.prometheus.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "udpchat.fullname" . }}-prometheus
  labels:
    {{- include "udpchat.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts: [ prometheus.{{ include "udpchat.host.root" . }} ]
      secretName: {{ include "udpchat.tlsSecretName" . }}
  rules:
    - host: prometheus.{{ include "udpchat.host.root" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "udpchat.name.prometheus" . }}
                port: { number: 9090 }
{{- end }}
