{{- /*
This template is intentionally OFF by default.
Prefer using an existing Secret applied by your deploy script:
  kubectl -n <ns> apply -f deploy/helm/chart/secret.yaml
and then set:
  existingAppSecret:
    enabled: true
    name: udpchat-app

Only use this template if you *really* want Helm to create the Secret.
Turn it on with:
  --set appSecret.enabled=true
Optionally set:
  --set appSecret.name=udpchat-app
  --set appSecret.data.JWT_ISSUER="udpchat"
  --set-file appSecret.files[0].key=JWT_SECRET appSecret.files[0].path=secret.jwt
*/ -}}
{{- if and (not .Values.existingAppSecret.enabled) .Values.appSecret.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-app" (include "udpchat.fullname" .)) .Values.appSecret.name }}
  labels:
    {{- include "udpchat.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- /* Inline key=value pairs (pass via --set or a CI secret manager). */ -}}
  {{- with .Values.appSecret.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}

  {{- /* File-backed keys: read files from the chart context.
        Example in values/CLI:
          appSecret:
            files:
              - key: JWT_SECRET
                path: secret.jwt
        Ensure the file exists in deploy/helm/chart/ and is git-ignored + helm-ignored. */ -}}
  {{- range $i, $f := (default list .Values.appSecret.files) }}
  {{ $f.key }}: |-
    {{- ($.Files.Get $f.path) | nindent 4 }}
  {{- end }}

{{- end }}
