{{- if or (include "udpchat.isTesting" . | eq "true") (ne (include "udpchat.currentColour" .) "") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "udpchat.name.nginx" . }}
  labels:
    {{- include "udpchat.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
    {{- $col := include "udpchat.currentColour" . }}
    {{- if $col }}
    app.kubernetes.io/color: {{ $col }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "udpchat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
    {{- if $col }}
    app.kubernetes.io/color: {{ $col }}
    {{- end }}
  ports:
    - name: http
      port: 80
      targetPort: {{ default 80 .Values.nginx.port }}
      protocol: TCP
{{- end }}