{{- if or (include "udpchat.isTesting" . | eq "true") (ne (include "udpchat.currentColour" .) "") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "udpchat.name.udp" . }}
  labels:
    {{- include "udpchat.labels" . | nindent 4 }}
    app.kubernetes.io/component: udp-server
    {{- $col := include "udpchat.currentColour" . }}
    {{- if $col }}
    app.kubernetes.io/color: {{ $col }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "udpchat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: udp-server
    {{- if $col }}
    app.kubernetes.io/color: {{ $col }}
    {{- end }}
  ports:
    - name: udp
      port: {{ default 9999 .Values.udp.port }}
      targetPort: {{ default 9999 .Values.udp.port }}
      protocol: UDP
{{- end }}