{{- if and (include "udpchat.isTesting" . | ne "true") .Values.monitoring.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  labels:
    {{- include "udpchat.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    {{- include "udpchat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
{{- end }}
