{{- if .Values.testServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: test-server
  labels:
    {{- include "udpchat.labels" . | nindent 4 }}
    app.kubernetes.io/component: test-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "udpchat.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: test-server
{{- end }}
