version: '3.8'

services:
  postgresql:
    image: postgres:15-alpine
    container_name: udpchat_postgresql
    environment:
      POSTGRES_DB: DB_NAME=${DB_NAME:-udpchat}
      POSTGRES_USER: ${DB_USER:-udpchat_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-udpchat_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U udpchat_user -d udpchat"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
