apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: ${LETSENCRYPT_EMAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-issuer-account-key
    preferredChain: "ISRG Root X1"
    solvers:
      - selector:
          dnsZones:
            - ${DOMAIN}
        dns01:
          azureDNS:
            hostedZoneName: ${DOMAIN}
            resourceGroupName: ${RESOURCE_GROUP}
            subscriptionID: ${SUBSCRIPTION_ID}
            tenantID: ${TENANT_ID}
            clientID: ${APP_ID}
            clientSecretSecretRef:
              name: le-azure-dns
              key: client-secret
