apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-udpchat
spec:
  secretName: wildcard-udpchat-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.${DOMAIN}"
    - "${DOMAIN}"
