apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://172.18.0.3:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
      queryTimeout: 60s
      timeInterval: 5s
